
#spring.datasource.url=jdbc:h2:mem:testdb

spring:
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  thymeleaf:
    cache: false
  thymeleaf3:
    decoupled-logic: true
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000
  datasource:
    url: jdbc:mysql://localhost:3306/lineup
    username: ${LINEUP_DB_ID}
    password: ${LINEUP_DB_PW}
    driver-class-name: com.mysql.cj.jdbc.Driver
#  sql:
#    init:
#      mode: always

debug: false

server:
  error:
    whitelabel:
      enabled: false

logging.level:
  org:
    hibernate:
      type:
        descriptor:
          sql:
            org.hibernate.type.descriptor.sql.BasicBinder : trace
    springframework:
      web.servlet : debug
cloud:
  aws:
    s3:
      bucket: image-test-suyoung
      dir: /stable-diffusion
    region:
      static: ap-northeast-2
    stack:
      auto: false